<!-- TOC -->

- [错误处理](#错误处理)
    - [panic](#panic)
    - [Option](#option)
        - [unwrap](#unwrap)
        - [map](#map)
        - [unwrap_or](#unwrap_or)
        - [and_then](#and_then)
    - [Result](#result)
        - [使用try!](#使用try)

<!-- /TOC -->

# 错误处理
Rust的所有权机制，为安全的编程语言打开了一扇门；Rust的错误处理，为严谨的编程逻辑打开了另一扇门。Rust抛弃了try-catch这样的异常处理机制，那么，它新的机制又有什么魅力呢？为什么说Rust的错误处理是一门艺术呢？一起来学习一下吧。  

## panic
首先说，panic是一个简单但并不是一个好的错误处理方法，因为它强制了终止了程序。
看下面的代码：
```rust
fn main() 
{
    panic!("abc");
}
```
程序直接调用了panic宏，运行时会输出以下内容：
```
thread 'main' panicked at 'abc', panic.rs:3:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
设置了RUST_BACKTRACE=1的环境变量后，得到了以下输出：
```
thread 'main' panicked at 'abc', panic.rs:3:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at src\libstd\sys\windows\backtrace/mod.rs:65
             at src\libstd\sys_common/backtrace.rs:69
   1: std::panicking::default_hook::{{closure}}
             at src\libstd\sys_common/backtrace.rs:58
             at src\libstd/panicking.rs:381
   2: std::panicking::default_hook
             at src\libstd/panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:577
   4: std::panicking::begin_panic
   5: panic::main
   6: _rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:99
   7: std::rt::lang_start
             at src\libstd/panicking.rs:459
             at src\libstd/panic.rs:361
             at src\libstd/rt.rs:59
   8: main
   9: _tmainCRTStartup
  10: mainCRTStartup
  11: unit_addrs_search
```
输出不可谓不详细，但是只能在像windows蓝屏那样遇到不能解决的问题时才可以使用。

## Option
Option 是Rust的系统类型，一个枚举，它与Rust强大的模式匹配紧密的结合在一起，优雅的处理值不存在的可能，它强制Rust检测和处理值不存在的情况。
Option的原型定义如下：
```rust
enum Option<T> {
    None,
    Some(T),
}
```
一般的，Option被用作函数的返回值，当值存在时，返回Some(T)，不存在时返回None。如：
```rust
fn substr(string:&str, sub:char) -> Option<usize>
{
    for (i, c) in string.char_indices()
    {
        if c == sub
        {
            return Some(i);
        }
    }
    
    None
}

fn main()
{
    match substr("abcd", 'c') {
        Some(i) => println!("找到该字母，位于第{}个", i),
        None => println!("没有找到该字母"),
    }

    match substr("abcd", 'e') {
        Some(i) => println!("找到该字母，位于第{}个", i),
        None => println!("没有找到该字母"),
    }
}
```

模式匹配虽然很高大上，但总让人感觉比较臃肿。Rust对上面的模式匹配进行了封装，提供了一些更高级、更优雅的方法。

### unwrap
最简单的封装是unwrap，它在不是None的时候返回Some的值，是None的时候panic。如：
```rust
fn substr(string:&str, sub:char) -> Option<usize>
{
    for (i, c) in string.char_indices()
    {
        if c == sub
        {
            return Some(i);
        }
    }
    
    None
}

fn main()
{
    println!("{}", substr("abcd", 'c').unwrap());

    println!("{}", substr("abcd", 'e').unwrap());
}
```
是不是看上去简洁了很多，但是，因为它使用panic，还不是一个好的方式。

### map
map允许传入一个闭包，当值为None时，不用执行闭包，当值不为None时执行，如：
```rust
fn substr(string:&str, sub:char) -> Option<usize>
{
    for (i, c) in string.char_indices()
    {
        if c == sub
        {
            return Some(i);
        }
    }
    
    None
}

fn main()
{
    substr("abcd", 'c').map(|i| println!("{:?}", i));

    substr("abcd", 'e').map(|i| println!("{:?}", i));
}
```

### unwrap_or
与unwrap直接panic不同，unwrap_or提供了一个默认值，当Option的值不为None时，返回该值，为None时返回默认值。如：
```rust
fn substr(string:&str, sub:char) -> Option<usize>
{
    for (i, c) in string.char_indices()
    {
        if c == sub
        {
            return Some(i);
        }
    }
    
    None
}

fn main()
{
    println!("{:?}", substr("abcd", 'c').unwrap_or(0));

    println!("{:?}", substr("abcd", 'e').unwrap_or(0));
}
```

### and_then
and_then与map相似，都可以传入一个函数，不同是，要求函数的返回值必需也是一个Option。如：
```rust
fn substr(string:&str, sub:char) -> Option<usize>
{
    for (i, c) in string.char_indices()
    {
        if c == sub
        {
            return Some(i);
        }
    }
    
    None
}

fn main()
{
    substr("abcd", 'c').and_then(|i| Some(i));

    substr("abcd", 'e').and_then(|i| Some(i));
}
```

## Result
比起上面的Option，Rust还提供了一个Result，它是比Option更为通用的一个错误版本，比起Option的None，Result可以提供一个错误信息，使程序更方便调试与错误的追踪。  
Option更多的描述了某事物可能不存在，而Result则是描述做某件事出错了。
字符串转int的函数就会返回Result，我们来看个例子：
```rust
fn print(s: &str)
{
    match s.parse::<i32>()
    {
        Ok(n) => println!("{}", n),
        Err(e) => println!("{}", e),
    }
}

fn main()
{
    print("10");
    print("ttt");
}
```
该例子输出为：
```
10
invalid digit found in string
```
与Option类似，Result也提供一系列如unwrap、map等简化处理。

### 使用try!
当编写的代码调用很多的返回 Result 类型的函数时，错误处理就变得比较冗长。此时，可以使用Rust提供的try!宏来减少代码量。如下面的例子：
```rust
fn atoi(s: &str) -> Result<i32, std::num::ParseIntError>
{
    let n = try!(s.parse::<i32>());
    Ok(n)
}

fn main()
{
    println!("{:?}", atoi("10"));
    println!("{:?}", atoi("ttt"));
}
```
该代码只是包了一下s.parse::\<i32\>，没有什么实际作用，只是演示try!的使用。当try!中的语句正常（返回OK())时try!不用做任何事件，当遇到Err时，会使调用try!的函数提前返回相应的Err。  
值得注意的是，只能在返回Result的函数中使用 try！，这意味着不能在main()中使用try!，因为main()不返回任何值。  
try!与其它语言的异常处理不同，其它语言抛出异常时，就不再有返回值，异常处理是打乱程序逻辑的一套规则，而try!是让函数提前返回，还是通过返回值来判断函数的执行情况。 